/**
 * Storage abstraction for uploaded media.
 *
 * Keys are relative, slash-separated paths generated by the server
 * (e.g. `tours/2026/10/<uuid>.webp`) and never come from user input.
 * `LocalDiskStorage` is the default; an S3-compatible implementation can
 * be added by implementing this interface (PutObject/GetObject/DeleteObject)
 * and returning it from `getStorage()` based on an env var.
 */
export type StoredObject = {
  body: Buffer;
  contentType: string;
  size: number;
};

export interface Storage {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
}

const SAFE_SEGMENT = /^[a-zA-Z0-9][a-zA-Z0-9._-]*$/;

/**
 * Returns the normalized key, or null if it could escape the storage root
 * (traversal, absolute paths, null bytes, hidden files, empty segments).
 */
export function normalizeKey(key: string): string | null {
  if (!key || key.length > 512 || key.includes("\0") || key.includes("\\")) return null;
  const segments = key.split("/");
  if (segments.some((segment) => !SAFE_SEGMENT.test(segment) || segment.includes(".."))) {
    return null;
  }
  return segments.join("/");
}

const contentTypes: Record<string, string> = {
  webp: "image/webp",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  avif: "image/avif",
};

export function contentTypeForKey(key: string): string | null {
  const extension = key.split(".").pop()?.toLowerCase() ?? "";
  return contentTypes[extension] ?? null;
}
